services:
  patients-api:
    build:
      context: ./services/patients
      dockerfile: Dockerfile
    volumes:
      - ./services/patients:/home/node/app
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/patients
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - postgres
      #- elasticsearch
    ports:
      - "3000:3000"

  doctors-api:
    build:
      context: ./services/doctors
      dockerfile: Dockerfile
    volumes:
      - ./services/doctors:/home/node/app
    environment:
      - PORT=3001
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/doctors
    depends_on:
      - rabbitmq
      - postgres
      #- elasticsearch
    ports:
      - "3001:3001"

  appointments-api:
    build:
      context: ./services/appointments
      dockerfile: Dockerfile
    volumes:
      - ./services/appointments:/home/node/app
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/appointments
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - postgres
      #- elasticsearch
    ports:
      - "3002:3002"

  notification-services:
    build:
      context: ./services/notifications
      dockerfile: Dockerfile
    volumes:
      - ./services/notifications:/home/node/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/patients
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - postgres
      #- elasticsearch

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=patients
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
  #   environment:
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - CLI_JAVA_OPTS=-Xms2g -Xmx2g
  #     - xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.13.4
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

volumes:
  postgres_data:
  es_data:
